import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // Manual sidebar for the Autonomous Humanoid Robotics Book
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1/1.1-ros2-architecture-dds',
        'module-1/1.2-nodes-topics-services-actions',
        'module-1/1.3-python-agents-rclpy',
        'module-1/1.4-humanoid-modeling-urdf-xacro'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/2.1-gazebo-physics-simulation',
        'module-2/2.2-sensors-in-simulation',
        'module-2/2.3-human-robot-interaction-hri',
        'module-2/2.4-digital-twin-validation'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3/3.1-introduction-to-whole-body-control',
        'module-3/3.2-kinematic-control-and-inverse-kinematics',
        'module-3/3.3-dynamics-and-force-control',
        'module-3/3.4-training-and-evaluation'
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4/4.1-voice-to-action-pipelines',
        'module-4/4.2-language-grounding-robotics',
        'module-4/4.3-llm-based-cognitive-planning',
        'module-4/4.4-capstone-project-autonomous-humanoid'
      ],
      collapsed: false,
    },
  ],
};

export default sidebars;
